import { Helmet } from "react-helmet-async";
import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <>
      <Helmet>
        <title>Terms &amp; Conditions — Student Hub</title>
        <meta name="description" content="Terms and Conditions for using Student Hub — the free study platform for Nepal students." />
      </Helmet>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8">
        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-blue-600 mb-6 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back
        </Link>

        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 sm:p-10">
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-2">Terms &amp; Conditions</h1>
          <p className="text-gray-400 text-sm mb-8">Last updated: May 2026</p>

          <div className="prose prose-gray max-w-none text-sm leading-relaxed space-y-6">
            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">1. Acceptance of Terms</h2>
              <p className="text-gray-600">By accessing or using Student Hub ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">2. Eligibility</h2>
              <p className="text-gray-600">Student Hub is intended for students in Grades 9–12 (approximately ages 14–18). By using the Platform, you confirm that you are at least 13 years of age. If you are under 18, you should have parental consent to use this Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">3. Account Registration</h2>
              <p className="text-gray-600">You must register using a valid Google account. You are responsible for maintaining the confidentiality of your account. You agree to provide accurate information during registration, including your correct grade level. One person may hold only one account.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">4. Use of the Platform</h2>
              <p className="text-gray-600">You agree to use Student Hub only for lawful educational purposes. You must not:</p>
              <ul className="list-disc pl-5 text-gray-600 space-y-1 mt-2">
                <li>Attempt to manipulate study statistics, streaks, or leaderboard rankings</li>
                <li>Upload, share, or distribute inappropriate, offensive, or copyrighted content</li>
                <li>Attempt to hack, reverse-engineer, or disrupt the Platform</li>
                <li>Use automated bots or scripts to interact with the Platform</li>
                <li>Impersonate other users or create fake accounts</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">5. AI Assistant (Nep AI)</h2>
              <p className="text-gray-600">Nep AI is provided as an educational aid only. The responses generated by Nep AI may not always be accurate. Always verify information from official textbooks and teachers. Do not use Nep AI for any purpose other than educational support.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">6. Intellectual Property</h2>
              <p className="text-gray-600">All content on Student Hub, including notes, questions, and platform design, is owned by Student Hub or its content providers. You may use this content for personal educational purposes only. Redistribution, commercial use, or reproduction without permission is strictly prohibited.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">7. Advertisements</h2>
              <p className="text-gray-600">Student Hub displays advertisements through Google AdSense to support free access for students. Advertisements are clearly marked and separate from educational content. We are not responsible for the content of third-party advertisements.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">8. Limitation of Liability</h2>
              <p className="text-gray-600">Student Hub is provided "as is" without warranties of any kind. We do not guarantee uninterrupted access or that the Platform will be free from errors. We shall not be liable for any loss of data, study progress, or indirect damages arising from the use of the Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">9. Termination</h2>
              <p className="text-gray-600">We reserve the right to suspend or terminate accounts that violate these Terms. You may delete your account at any time by contacting us through the Contact page.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">10. Changes to Terms</h2>
              <p className="text-gray-600">We may update these Terms from time to time. Continued use of the Platform after changes constitutes acceptance of the new Terms. We will notify users of significant changes via announcements on the Platform.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">11. Governing Law</h2>
              <p className="text-gray-600">These Terms are governed by the laws of Nepal. Any disputes shall be resolved in the courts of Nepal.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-gray-800 mb-2">12. Contact</h2>
              <p className="text-gray-600">For questions about these Terms, please visit our <Link href="/contact" className="text-blue-500 hover:underline">Contact page</Link>.</p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
